Newbranch
madhumitha13579/online-shopping pull request #1
Opened 2022-12-09 04:58 UTC by madhumitha13579

2022-12-09 07:43 UTC, Sushmitha-Vk requested changes

2022-12-09 07:43 UTC, Sushmitha-Vk commented on src/app/dashboard/dashboard.component.ts
> +    dialogRef.afterClosed().subscribe((details: any) => ( `output, ${details}`) )
what is this output...? was it not part of console.log...?

2022-12-09 07:43 UTC, Sushmitha-Vk commented on src/app/header/header.component.ts
>      this.a =localStorage.getItem('email')
why a..? why not changed to proper name?

2022-12-09 07:43 UTC, Sushmitha-Vk commented on src/app/header/header.component.ts
>      this.l=((this.name.split(' ',2))[1])[0]
same here

2022-12-09 07:43 UTC, Sushmitha-Vk commented on src/app/login/login.component.ts
>      this.service.login(data).subscribe((d:any)=>{
d naming

2022-12-09 07:43 UTC, Sushmitha-Vk commented on src/app/stepper/stepper.component.ts
>      //email:['', Validators.required],
remove comments

2022-12-09 07:43 UTC, Sushmitha-Vk commented on src/app/wishlist/wishlist.component.ts
> +    this.dataSource = this.serv.dataEvent$.pipe(map((n: any) => {
n..?

2022-12-09 07:43 UTC, Sushmitha-Vk commented on src/app/wishlist/wishlist.component.ts
> +    dialogRef.afterClosed().subscribe((details: any) => { })
details not used, why is it declared..?

2022-12-12 08:44 UTC, madhumitha13579 commented on src/app/dashboard/dashboard.component.ts
> +    dialogRef.afterClosed().subscribe((details: any) => ( `output, ${details}`) )
changes corrected

2022-12-12 08:44 UTC, madhumitha13579 commented on src/app/header/header.component.ts
>      this.a =localStorage.getItem('email')
changes corrected

2022-12-12 08:45 UTC, madhumitha13579 commented on src/app/header/header.component.ts
>      this.l=((this.name.split(' ',2))[1])[0]
changes corrected

2022-12-12 08:45 UTC, madhumitha13579 commented on src/app/login/login.component.ts
>      this.service.login(data).subscribe((d:any)=>{
changes corrected

2022-12-12 08:45 UTC, madhumitha13579 commented on src/app/stepper/stepper.component.ts
>      //email:['', Validators.required],
corrected mam

2022-12-12 08:46 UTC, madhumitha13579 commented on src/app/wishlist/wishlist.component.ts
> +    this.dataSource = this.serv.dataEvent$.pipe(map((n: any) => {
corrected changes

2022-12-13 06:20 UTC, Sushmitha-Vk approved these changes

2022-12-13 07:06 UTC, merged